export const ProductDetailsMetaData = [
  {
    id: "8b9db4c3-50e6-47a5-942b-d941e8cb61a2",
    lineupName: "Pearl White",
    color: "white",
    price: 1450,
    images: {
      original: "/ice-white-product.jpeg",
      thumbnail: "/ice-white-product.jpeg",
    },
    cartImage: "/ice-white-cart.jpeg",
  },
  {
    id: "3163f84a-75e2-406b-bc01-7e4110610338",
    lineupName: "Matte Black",
    color: "black",
    price: 1550,
    images: {
      original: "/ice-black.jpeg",
      thumbnail: "/ice-black.jpeg",
    },
    cartImage: "/ice-black-cart.jpeg",
  },
];

export const bangladeshDistricts = [
  { value: "Bagerhat", label: "Bagerhat" },
  { value: "Bandarban", label: "Bandarban" },
  { value: "Barguna", label: "Barguna" },
  { value: "Barisal", label: "Barisal" },
  { value: "Bhola", label: "Bhola" },
  { value: "Bogra", label: "Bogra" },
  { value: "Brahmanbaria", label: "Brahmanbaria" },
  { value: "Chandpur", label: "Chandpur" },
  { value: "Chapai Nawabganj", label: "Chapai Nawabganj" },
  { value: "Chattogram (Chittagong)", label: "Chattogram (Chittagong)" },
  { value: "Chuadanga", label: "Chuadanga" },
  { value: "Comilla", label: "Comilla" },
  { value: "Cox's Bazar", label: "Cox's Bazar" },
  { value: "Dhaka", label: "Dhaka" },
  { value: "Dinajpur", label: "Dinajpur" },
  { value: "Faridpur", label: "Faridpur" },
  { value: "Feni", label: "Feni" },
  { value: "Gaibandha", label: "Gaibandha" },
  { value: "Gazipur", label: "Gazipur" },
  { value: "Gopalganj", label: "Gopalganj" },
  { value: "Habiganj", label: "Habiganj" },
  { value: "Jamalpur", label: "Jamalpur" },
  { value: "Jashore (Jessore)", label: "Jashore (Jessore)" },
  { value: "Jhalokati", label: "Jhalokati" },
  { value: "Jhenaidah", label: "Jhenaidah" },
  { value: "Joypurhat", label: "Joypurhat" },
  { value: "Khagrachari", label: "Khagrachari" },
  { value: "Khulna", label: "Khulna" },
  { value: "Kishoreganj", label: "Kishoreganj" },
  { value: "Kurigram", label: "Kurigram" },
  { value: "Kushtia", label: "Kushtia" },
  { value: "Lakshmipur", label: "Lakshmipur" },
  { value: "Lalmonirhat", label: "Lalmonirhat" },
  { value: "Madaripur", label: "Madaripur" },
  { value: "Magura", label: "Magura" },
  { value: "Manikganj", label: "Manikganj" },
  { value: "Meherpur", label: "Meherpur" },
  { value: "Moulvibazar", label: "Moulvibazar" },
  { value: "Munshiganj", label: "Munshiganj" },
  { value: "Mymensingh", label: "Mymensingh" },
  { value: "Naogaon", label: "Naogaon" },
  { value: "Narail", label: "Narail" },
  { value: "Narayanganj", label: "Narayanganj" },
  { value: "Narsingdi", label: "Narsingdi" },
  { value: "Natore", label: "Natore" },
  { value: "Nawabganj", label: "Nawabganj" },
  { value: "Netrakona", label: "Netrakona" },
  { value: "Nilphamari", label: "Nilphamari" },
  { value: "Noakhali", label: "Noakhali" },
  { value: "Pabna", label: "Pabna" },
  { value: "Panchagarh", label: "Panchagarh" },
  { value: "Patuakhali", label: "Patuakhali" },
  { value: "Pirojpur", label: "Pirojpur" },
  { value: "Rajbari", label: "Rajbari" },
  { value: "Rajshahi", label: "Rajshahi" },
  { value: "Rangamati", label: "Rangamati" },
  { value: "Rangpur", label: "Rangpur" },
  { value: "Satkhira", label: "Satkhira" },
  { value: "Shariatpur", label: "Shariatpur" },
  { value: "Sherpur", label: "Sherpur" },
  { value: "Sirajganj", label: "Sirajganj" },
  { value: "Sunamganj", label: "Sunamganj" },
  { value: "Sylhet", label: "Sylhet" },
  { value: "Tangail", label: "Tangail" },
  { value: "Thakurgaon", label: "Thakurgaon" },
  // You can continue to add more districts here...
];
